# POST http://localhost:6868/login
# Content-Type: application/json


# {
#     "email": "user1@gmail.com",
#     "password": "123456"
# }

# GET http://localhost:6868/token

# GET http://localhost:6868/users
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsIm5hbWUiOiJ1c2VyMSIsImVtYWlsIjoidXNlcjFAZ21haWwuY29tIiwicm9sZSI6MSwiaWF0IjoxNzMyMTEwODc1LCJleHAiOjE3MzIxMTE0NzV9.5uvssTHPs6IjwbfsJ5p3Bmrr-6hegs-ON9eh9mS6JJ8

# ---------------------------------------------

# test post category

# POST http://localhost:6868/categories
# Content-Type: application/json


# {
#     "name": "aaaaa",
#     "description": "123456"
# }

# ---------------------------------------------


# test post product

# POST http://localhost:6868/products
# Content-Type: application/json


# {
#     "name": "aaaaa",
#     "description": "123456a",
#     "price": "2222222",
#     "stock": "99",
#     "categoryId": "9"
# }


# ---------------------------------------------







# --------------------------------

# POST http://localhost:6868/users
# Content-Type: application/json

# {
#     "name":"user3",
#     "email": "user3@gmail.com",
#     "password": "123456",
#     "confPassword": "123456"
# }



# GET http://localhost:6868/stats/users

# GET http://localhost:6868/stats/products

# GET http://localhost:6868/stats/orders

# DELETE http://localhost:6868/logout
